# Models to evaluate
models:
  - "anthropic/claude-sonnet-4.6"
  - "deepseek/deepseek-chat-v3-0324"
  - "deepseek/deepseek-r1-0528"
  - "google/gemini-2.5-flash"
  - "google/gemini-3.1-pro-preview"
  - "meta-llama/llama-3.3-70b-instruct"
  # - "meta-llama/llama-4-scout"
  - "meta-llama/llama-4-maverick"
  - "minimax/minimax-m2.5"
  # - "mistralai/mistral-nemo"
  - "openai/gpt-5"
  - "openai/gpt-5-nano"
  # - "openai/gpt-5.4"
  - "openai/gpt-oss-20b"
  - "openai/gpt-oss-120b"
  - "qwen/qwen3-235b-a22b-2507"
  - "qwen/qwen3-235b-a22b-thinking-2507"
  - "x-ai/grok-4"
  - "x-ai/grok-4-fast"
  # - "x-ai/grok-4.20-beta"
